replicaCount: 2

config:
  APP_ENV: stage


resourceQuota:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "15"
service:
  enabled: false

ingress:
  enabled: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  requests:
    cpu: 300m
    memory: 768Mi
  limits:
    cpu: 1200m
    memory: 3Gi
